### ISSUE TITLE
footnote option 

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#77] opened 2020-05-13 21:06 UTC
Once pmx_report generates the listing of plots with footnote == TRUE, it seems that afterwards when user wants to generate individual GOF plots using pmx_plot_XXX, then all plots are generated subsequently with footnote.

I would expect footnote to be a local variable for pmx_report, NOT for the individual GOF plots (see enclosed). Please confirm and fix adequately the bug.

```
setwd('/home/biethbr1/SVN/ggPMX_doc/')
WORK_DIR    = '/home/biethbr1/SVN/ggPMX_doc/USER_EXAMPLES/MLX/PK_WITH_COVARIATE/RESULTS'
input_file = '/home/biethbr1/SVN/ggPMX_doc/USER_EXAMPLES/MLX/PK_WITH_COVARIATE/warfarin_data3.csv'
ctr <- pmx(
  sys="mlx",
  config='standing',
  directory = WORK_DIR, 
  input = input_file, 
  dv = "dv",
  cats=c("AGECAT"),
  dvid='dvid')

ctr %>% pmx_report(name='Diagnostics_Plots2',save_dir = '/home/biethbr1/SVN/ggPMX_doc/USER_EXAMPLES/MLX/PK_WITH_COVARIATE',output_type='plots',footnote=TRUE)

pdf('Test.pdf',10,6)
ctr %>% pmx_plot_ebe_box()
ctr %>% pmx_plot_individual(npage=NULL)
dev.off()
```
(Old Ticker #221)

**Comment by tynesjo** [comment] 2020-10-23 10:07
Failed to reproduce; closing.

```

ctr <- theophylline()

# Creates report with footnotes
ctr %>%
pmx_report(
  name='footnote-test',
  save_dir ='/tmp/',
  output_type='plots',
  footnote=TRUE,
  template='ggPMX/inst/rmarkdown/templates/standing'
)

# Returns FALSE
ctr[["footnote"]]

# Creates plot without footnotes
ctr %>% pmx_plot_individual(npage=NULL)
# Creates plot with footnotes
TRUE -> ctr[["footnote"]]
ctr %>% pmx_plot_individual(npage=NULL)
```

Suspect the following lines in the `pmx_report` function have addressed this:

```
on.exit({
  remove_temp_files(contr$save_dir)
  contr$footnote <- FALSE
})
```

But there are no comments there so not certain what the intended effect is.

**Closed by tynesjo** 2020-10-23 10:07 UTC
Labels: bug

**Comment by biethbr1** [comment] 2020-10-26 14:37
I confirm - bug not there anymore
