### ISSUE TITLE
push cats vs EBE on different pages

### ISSUE THREAD

**Issue by combefr1** [ggPMXdevelopment/ggPMX#50] opened 2020-03-27 21:53 UTC
Hi folks

very nice package . I really like what we can do there. 
small question. I have a pretty ugly EBE vs covariates plot, due to a large labels for RACE and Ethnicity. 
would you have an advice to modify this?

![Annotation 2020-03-27 175121](https://user-images.githubusercontent.com/33521747/77803485-999cad80-7053-11ea-9043-3662a0a1df1e.png)

**Comment by mattfidler** [comment] 2020-03-30 17:05
Hi @combefr1 

This can be easily fixed with ggplot 3.3.0;  

See the blog:

https://www.tidyverse.org/blog/2020/03/ggplot2-3-3-0/


Then you can modify the plot by something like:

```R
ctr %>% pmx_plot_iwres_dens + scale_x_discrete(guide = guide_axis(n.dodge = 2))
```

**Comment by combefr1** [comment] 2020-03-30 18:44
Unfortunately, it seems that the guide argument already exists in the pmx_plot_eta_cats function:
   ctr %>% pmx_plot_eta_cats  + scale_x_discrete(guide = guide_axis(n.dodge = 2))
Error in discrete_scale(c("x", "xmin", "xmax", "xend"), "position_d",  : 
  formal argument "guide" matched by multiple actual arguments

**Comment by combefr1** [comment] 2020-03-30 20:04
as a workaround, I tried to change the labels

#user  settings for report
mySet=pmx_settings(is.draft=DRAFT_STATUS!= "Final", use.labels = TRUE, 
                  cats.labels = list(
                     RACE = c("Asian"= "As", "Black"="Bl", "Caucasian" = "Ca", "Other"= "Ot"), 
                     ETHN = c("Chinese" = "Ch", 
                              "Hispanic/Latino" = "Hi", 
                              "Indian (Indian subcontinent)" = "In", 
                              "Japanese" = "Ja", 
                              "Mixed Ethnicity" = "Mi", 
                              "Other"="Ot"),
                     JAP = c("0"="non-Japanese", "1"="japanese")
                     )
                   )

followed

ctr <- pmx_mlxtran(config = "standing", mlxpath, settings = mySet )


no changes

**Comment by baltcir1** [comment] 2020-03-31 06:03
Might be a bug. We are following up. Thanks for spotting this out!

**Comment by KZRKZR** [comment] 2020-11-26 14:26
Hi @combefr1 
I tried your example and can't reproduce the issue.
```
mySet=pmx_settings(is.draft=TRUE)
mlxpath <- file.path(system.file(package = "ggPMX"),
                     "testdata","1_popPK_model","project.mlxtran")
ctr <- pmx_mlxtran(mlxpath, config = "standing", settings = mySet)

ctr %>% pmx_plot_eta_cats(is.shrink = FALSE) + 
        scale_x_discrete(labels=c("88" = "Other"),
                         guide = guide_axis(n.dodge = 2)
                        )

ctr %>% pmx_plot_eta_cats(is.shrink = FALSE) + 
  scale_x_discrete(
                   guide = guide_axis(n.dodge = 2)
  )
```
Result:
![image](https://user-images.githubusercontent.com/10551498/100361859-58ee9d00-3003-11eb-839f-364261a032ee.png)
For changing labels in pmx_plot_eta_cats we could use this approach:
```
ctr %>% pmx_plot_eta_cats(is.shrink = FALSE) + 
        scale_x_discrete(labels=c("88" = "Other"),
                         guide = guide_axis(n.dodge = 2)
                        )
```
Result:
![image](https://user-images.githubusercontent.com/10551498/100362357-f9dd5800-3003-11eb-8d31-0eea958f2470.png)
Could you please provide a reproducible example.

**Comment by KZRKZR** [comment] 2021-01-20 10:34
Hi @baltcir1 and @combefr1 
If this issue is still actual, could you please help to reproduce it?

Best regards,
Kostia

**Comment by baltcir1** [comment] 2021-01-20 11:27
Hi @KZRKZR, next week, @combefr1 will check again the above syntax you propose on his example. We keep you posted. Thanks.

**Comment by tynesjo** [comment] 2021-03-19 11:50
@baltcir1, @combefr1  feel free to reopen if a reproducible example becomes available
Thanks

**Closed by tynesjo** 2021-03-19 11:50 UTC
Labels: bug, help wanted
