### ISSUE TITLE
Controller error messages when adding a second endpoint 

### ISSUE THREAD

**Issue by tmss1** [ggPMXdevelopment/ggPMX#289] opened 2022-11-11 15:49 UTC
**Describe the bug**
No issues for the endpoint=1, but error messages return for the endpoint=2.  Are they important?

![image](https://user-images.githubusercontent.com/32617414/201376008-c4169e3d-f14f-4d6f-840c-32409189debb.png)

**Comment by tynsci** [comment] 2023-03-16 09:34
@tmss1, thanks for reporting
- yes this is a problem, and a duplicate of #202, work on which is in progress
- closing as duplicate

**Closed by tynsci** 2023-03-16 09:34 UTC
Labels: bug
