### ISSUE TITLE
dv_pred , dv_ipred

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#59] opened 2020-05-13 19:26 UTC
When customizing identity_line, it is not shown.
When using scale_x_log10 = T and scale_y_log10 = T, ranges are ignored.
When using scale_x_log10 = T and scale_y_log10 = T, the identity line is not shown

(Linked to old ticket #238)

**Comment by tynesjo** [comment] 2020-11-06 09:25
Moving to close because it has not been possible to reproduce any of these bugs.

Using following control object:

```r
ctr <- theophylline(
  settings=pmx_settings(
    cats.labels=list(SEX=c("0"="M","1"="F")), 
    use.labels=TRUE,
    use.identity_line=TRUE
  )
)

# Issue: customizing identity line makes it disappear

# Failed to reproduce.

p0a <-
  ctr %>%
  pmx_plot_dv_pred(
    identity_line=list(color="red", linetype=3)
  ) 

p0b <-
  ctr %>%
  pmx_plot_dv_ipred(
    identity_line=list(color="red", linetype=3)
  ) 

# Issue: When using scale_x_log10 = T and scale_y_log10 = T,
# the identity line is not shown

p1a <-
  ctr %>%
  pmx_plot_dv_pred(
    scale_x_log10=TRUE,
    scale_y_log10=TRUE
  ) 

p1b <-
  ctr %>%
  pmx_plot_dv_ipred(
    scale_x_log10=TRUE,
    scale_y_log10=TRUE
  ) 

# Failed to Reproduce.

### Issue: When using scale_x_log10 = T and scale_y_log10 = T, ranges are ignored.

p2a <-
  ctr %>%
  pmx_plot_dv_pred(
    ranges=list(
      x=c(250L, 350L),
      y=c(250L, 350L)
      )
  ) 

p2b <-
  ctr %>%
  pmx_plot_dv_ipred(
    ranges=list(
      x=c(250L, 350L),
      y=c(250L, 350L)
      )
  ) 

# Failed to reproduce
```

The resulting plots can be found below:

p0a
![p0a](https://user-images.githubusercontent.com/3072895/98349216-a03fca00-2011-11eb-9122-cb0d4a71e0ca.png)

p0b
![p0b](https://user-images.githubusercontent.com/3072895/98349237-a59d1480-2011-11eb-8de9-9452a0bf1a6e.png)

p1a
![p1a](https://user-images.githubusercontent.com/3072895/98349253-ad5cb900-2011-11eb-9ebd-bb5310fe4a44.png)

p1b
![p1b](https://user-images.githubusercontent.com/3072895/98349276-b3eb3080-2011-11eb-924e-f943846f8b5d.png)

p2a
![p2a](https://user-images.githubusercontent.com/3072895/98349294-b9e11180-2011-11eb-9752-a15caeebdfb5.png)

p2b
![p2b](https://user-images.githubusercontent.com/3072895/98349335-c2394c80-2011-11eb-8cc5-f86b05ba3dc9.png)

**Closed by tynesjo** 2020-11-06 09:25 UTC
Labels: bug
