### ISSUE TITLE
Facets don't work for VPC plots

### ISSUE THREAD

**Issue by margoal1** [ggPMXdevelopment/ggPMX#102] opened 2020-06-29 19:46 UTC
**This produces an error:**
ctr %>% pmx_plot_**vpc**(strat.facet = ~STUD)

Error in \`[.data.table`(dx, , stats::quantile(get(ind), probs = probs,  : 
  column or expression 2 of 'by' or 'keyby' is type language. Do not quote column names. Usage: DT[,sum(colC),by=list(colA,month(colB))]

**This works fine:**
ctr %>% pmx_plot_**npde_time**(strat.facet = ~STUD)

**Comment by sehamsick** [comment] 2020-10-13 12:59
Yes this issue is caused because the confidence intervals (CIs) need to be calculated for each categorical level in the VPC. So it's not simply a "graphical stratification". Currently, the function `vpc.data` requires a string input in `strat.facet` in order to calculate the CIs for each level.

It is possible to stratify using this syntax: `ctr %>% pmx_plot_vpc(strat.facet = "STUD")` (which is also possible for the other plots e.g. npde_time)

For the next version a fix is included, where `~STUD` is converted to `"STUD"` so that both options work.

**Attention!!!**
This code: `ctr %>% pmx_plot_vpc() + facet_wrap(~STUD)` will be executed without error or warning message.
This will result in just a "graphical stratification". By using this syntax, the graph is stratified but the CIs do not match the data!

**Comment by tynsci** [comment] 2022-05-11 09:56
- Using version 1.2.6 this bug can no longer be reproduced.
- Will add a testthat test for `pmx_plot_vpc` to prevent a regression of this error then move to close

**Closed** 2022-05-27 22:02 UTC
Labels: bug
